import {node,button,field,section,text,actionFor} from './tree.js';
import {renderExecutionProfile,renderAttachment,renderSessionMetadata} from './metadata.js';
export function renderInspector(state,actions){
 const find=(operation,...args)=>actionFor(actions,operation,...args);
 const act=(operation,label,...args)=>{const action=find(operation,...args);return action?button('inspector:action:'+operation+':'+JSON.stringify(args),label,action):null;};
 const children=[node('nav','inspector:tools',null,[act('refresh','刷新上下文'),act('syncThreads','同步会话')])];
 children.push(section('inspector:diagnostics','Agent 状态',state.diagnostics.map(item=>section('diagnostic:'+item.agent,item.label,[text('diagnostic:status:'+item.agent,`${item.status} · ${item.authState}`),text('diagnostic:version:'+item.agent,item.version),text('diagnostic:executable:'+item.agent,item.executable),text('diagnostic:message:'+item.agent,item.message),...(item.capabilities??[]).map((value,i)=>text('diagnostic:capability:'+item.agent+':'+i,value))]))));
 children.push(renderSessionMetadata(state.session,'inspector:session-metadata'),renderExecutionProfile(state.executionProfile,'inspector:execution-profile'),section('inspector:attachments','上下文附件',state.attachments.length?state.attachments.map(item=>renderAttachment(item,'inspector:attachment:'+item.id)):[text('inspector:no-attachments','发送前可在输入框添加文件或目录')]));
 const inventory=state.workspaceCapabilities;
 if(inventory)for(const [key,label] of [['instructions','指令'],['skills','技能'],['tools','工具'],['mcpServers','MCP 服务']])children.push(section('inventory:'+key,label,inventory[key].map((item,i)=>text('inventory:'+key+':'+i,`${item.name} · ${item.source}`))));
 if(inventory?.warnings.length)children.push(section('inventory:warnings','检查提示',inventory.warnings.map((value,i)=>text('inventory:warning:'+i,value))));
 children.push(section('inspector:threads','线程',state.threads.map(item=>text('thread:'+item.id,`${item.title??item.id} · ${item.status??''}${item.cwd?' · '+item.cwd:''}`))));
 children.push(section('inspector:artifacts','产物',state.artifacts.map(item=>node('article','artifact:'+item.id,null,[text('artifact:metadata:'+item.id,`${item.source} · ${item.mediaType} · ${item.size} 字节`),text('artifact:scope:'+item.id,item.turnId?'本轮 '+item.turnId:'会话级'),text('artifact:hash:'+item.id,item.contentHash?'内容摘要：'+item.contentHash:null),act('toggleArtifact',state.artifactPreview.artifactId===item.id?(state.artifactPreview.error?'重试产物':'收起产物'):'查看产物 '+item.source,item.id)]))));
 const preview=state.artifactPreview;
 if(preview.artifactId)children.push(section('inspector:preview','产物预览',[act('closeArtifact','关闭产物'),preview.loading?text('artifact:loading','正在读取产物'):null,text('artifact:error',preview.error),preview.content?node('pre','artifact:content',preview.content.content,[],{tabindex:'0'}):null,preview.content?.truncated?text('artifact:truncated','产物已截断'):null]));
 children.push(section('inspector:project-actions','工程动作',[act('newProjectAction','新建工程动作'),...state.projectActions.map(item=>node('article','project:'+item.id,null,[text('project:name:'+item.id,item.name),text('project:command:'+item.id,[item.program,...item.args].join(' ')),text('project:cwd:'+item.id,item.cwd),text('project:enabled:'+item.id,item.enabled?'已启用':'已禁用'),act('editProjectAction','编辑 '+item.name,item.id),act('deleteProjectAction','删除 '+item.name,item.id),act('runProjectAction','运行 '+item.name,item.id)]))]));
 const editor=state.projectEditor;
 if(editor.open)children.push(section('inspector:editor','编辑工程动作',[...['name','program','args','cwd'].map((key,i)=>field('project:field:'+key,['名称','程序','参数（JSON 数组）','工作目录'][i],editor[key],find('projectField',key),key==='args')),node('nav','project:kinds',null,['test','lint','build','custom'].map((kind,i)=>{const action=find('projectKind',kind);return button('project:kind:'+kind,['测试','检查','构建','自定义'][i],action,{'aria-pressed':String(editor.kind===kind)});})),text('project:save-error',editor.error),editor.saving?text('project:saving','正在保存'):null,act('saveProjectAction','保存工程动作'),act('closeProjectEditor','关闭编辑器')]));
 children.push(section('inspector:runs','运行记录',state.projectActionRuns.map(run=>node('article','run:'+run.id,null,[text('run:label:'+run.id,`${run.actionName??run.actionId} · ${run.status} · 退出码 ${run.exitCode??'—'}`),node('pre','run:output:'+run.id,run.output,[],{tabindex:'0'}),act('cancelProjectAction','取消运行',run.id)]))));
 const change=state.changeSet;
 if(change){
  children.push(section('inspector:changes','本轮变更',[text('change:status',`${change.attribution} · ${change.captureStatus}`),text('change:error',change.captureError),act('restoreTurn','恢复整轮',change.turnId),...change.files.map(file=>node('article','change:file:'+file.path,null,[text('change:path:'+file.path,file.path),act('showDiff','查看差异',change.turnId,file.path),...['stage','unstage','revert'].map((operation,i)=>act('fileAction',['暂存文件','取消暂存文件','恢复文件'][i],change.turnId,file.path,operation))])),...change.commands.map(command=>section('change:command:'+command.id,command.command??command.toolName??'命令',[text('change:command-status:'+command.id,command.status),node('pre','change:command-output:'+command.id,command.output)])),...change.verification.map(item=>section('change:verification:'+item.id,'验证 '+item.status,[node('pre','change:verification-output:'+item.id,item.output)]))]));
  if(state.fileDiff)children.push(section('inspector:diff',state.fileDiff.path,[text('change:diff-reason',state.fileDiff.reason),node('pre','change:diff-content',state.fileDiff.diff,[],{tabindex:'0'}),...state.fileDiff.hunks.map(hunk=>section('change:hunk:'+hunk.index,hunk.header,[node('pre','change:hunk-content:'+hunk.index,hunk.content),...['stage','unstage','revert'].map((operation,i)=>act('hunkAction',['暂存片段','取消暂存片段','恢复片段'][i],change.turnId,state.fileDiff.path,String(hunk.index),operation))]))]));
 }
 children.push(text('inspector:diff-error',state.fileDiffError),state.fileDiffLoading?text('inspector:diff-loading','正在读取差异'):null,section('inspector:checkpoints','检查点',state.checkpoints.map(item=>text('checkpoint:'+item.id,`${item.path} · ${item.available?'可用':item.reason??'不可用'}${item.baselineDirty?' · 基线已有修改':''}`))),section('inspector:restores','恢复记录',state.restoreOperations.map(item=>section('restore:'+item.id,item.status,[text('restore:restored:'+item.id,'已恢复：'+item.restored.join('、')),text('restore:conflicts:'+item.id,'冲突：'+item.conflicts.join('、')),text('restore:unsupported:'+item.id,'不支持：'+item.unsupported.join('、'))]))));
 return section('inspector','上下文',children);
}
