import {presentationTranslator} from './i18n.js';
import {formatNumber} from './i18n.generated.js';
import {node,button,field,section,text,actionFor} from './tree.js';
import {renderExecutionProfile,renderAttachment,renderSessionMetadata} from './metadata.js';
export function renderInspector(state,actions,locale='zh-CN'){
 const t=presentationTranslator(locale);
 const find=(operation,...args)=>actionFor(actions,operation,...args);
 const act=(operation,label,...args)=>{const action=find(operation,...args);return action?button('inspector:action:'+operation+':'+JSON.stringify(args),label,action):null;};
 const children=[node('nav','inspector:tools',null,[act('refresh',t('inspector.refresh')),act('syncThreads',t('external.syncSessions'))])];
 children.push(section('inspector:diagnostics',t('diagnostics.agents'),state.diagnostics.map(item=>section('diagnostic:'+item.agent,item.label,[text('diagnostic:status:'+item.agent,`${({ready:t('inspector.available'),missing:t('inspector.notInstalled'),error:t('inspector.error')})[item.status]??item.status} · ${({delegated:t('diagnostics.systemCredentials'),not_required:t('diagnostics.authNotRequired'),unknown:t('diagnostics.authUnknown')})[item.authState]??item.authState}`),text('diagnostic:version:'+item.agent,item.version),text('diagnostic:executable:'+item.agent,item.executable),text('diagnostic:message:'+item.agent,item.message),...(item.capabilities??[]).map((value,i)=>text('diagnostic:capability:'+item.agent+':'+i,value))]))));
 children.push(renderSessionMetadata(state.session,'inspector:session-metadata',locale),renderExecutionProfile(state.executionProfile,'inspector:execution-profile',locale),section('inspector:attachments',t('inspector.attachments'),state.attachments.length?state.attachments.map(item=>renderAttachment(item,'inspector:attachment:'+item.id,locale)):[text('inspector:no-attachments',t('external.attachmentHint'))]));
 const inventory=state.workspaceCapabilities;
 if(inventory)for(const [key,label] of [['instructions',t('inspector.instructions')],['skills',t('composer.category.skill')],['tools',t('role.tool')],['mcpServers',t('external.mcpServers')]])children.push(section('inventory:'+key,label,inventory[key].map((item,i)=>text('inventory:'+key+':'+i,`${item.name} · ${item.source}`))));
 if(inventory?.warnings.length)children.push(section('inventory:warnings',t('external.inspectionNotes'),inventory.warnings.map((value,i)=>text('inventory:warning:'+i,value))));
 children.push(section('inspector:threads',t('external.threads'),state.threads.map(item=>text('thread:'+item.id,`${item.title??item.id} · ${item.status??''}${item.cwd?' · '+item.cwd:''}`))));
 children.push(section('inspector:artifacts',t('search.kind.artifact'),state.artifacts.map(item=>node('article','artifact:'+item.id,null,[text('artifact:metadata:'+item.id,t('external.artifactMetadata',{source:item.source,mediaType:item.mediaType,size:formatNumber(locale,item.size)})),text('artifact:scope:'+item.id,item.turnId?t('external.turnScope',{turnId:item.turnId}):t('inspector.sessionLevel')),text('artifact:hash:'+item.id,item.contentHash?t('external.contentHash',{hash:item.contentHash}):null),act('toggleArtifact',state.artifactPreview.artifactId===item.id?(state.artifactPreview.error?t('external.retryArtifact'):t('external.collapseArtifact')):t('external.viewArtifact',{source:item.source}),item.id)]))));
 const preview=state.artifactPreview;
 if(preview.artifactId)children.push(section('inspector:preview',t('external.artifactPreview'),[act('closeArtifact',t('external.closeArtifact')),preview.loading?text('artifact:loading',t('external.loadingArtifact')):null,text('artifact:error',preview.error),preview.content?node('pre','artifact:content',preview.content.content,[],{tabindex:'0'}):null,preview.content?.truncated?text('artifact:truncated',t('external.artifactTruncated')):null]));
 children.push(section('inspector:project-actions',t('project.title'),[act('newProjectAction',t('external.newProjectAction')),...state.projectActions.map(item=>node('article','project:'+item.id,null,[text('project:name:'+item.id,item.name),text('project:command:'+item.id,[item.program,...item.args].join(' ')),text('project:cwd:'+item.id,item.cwd),text('project:enabled:'+item.id,item.enabled?t('app.enabled'):t('app.disabled')),act('editProjectAction',t('external.editNamed',{name:item.name}),item.id),act('deleteProjectAction',t('external.deleteNamed',{name:item.name}),item.id),act('runProjectAction',t('external.runNamed',{name:item.name}),item.id)]))]));
 const editor=state.projectEditor;
 if(editor.open)children.push(section('inspector:editor',t('external.editProjectAction'),[...['name','program','args','cwd'].map((key,i)=>field('project:field:'+key,[t('external.name'),t('external.program'),t('external.jsonArguments'),t('external.workingDirectory')][i],editor[key],find('projectField',key),key==='args')),node('nav','project:kinds',null,['test','lint','build','custom'].map((kind,i)=>{const action=find('projectKind',kind);return button('project:kind:'+kind,[t('external.test'),t('external.lint'),t('external.build'),t('external.custom')][i],action,{'aria-pressed':String(editor.kind===kind)});})),text('project:save-error',editor.error),editor.saving?text('project:saving',t('external.saving')):null,act('saveProjectAction',t('external.saveProjectAction')),act('closeProjectEditor',t('external.closeEditor'))]));
 children.push(section('inspector:runs',t('external.runHistory'),state.projectActionRuns.map(run=>node('article','run:'+run.id,null,[text('run:label:'+run.id,t('external.projectRunLabel',{name:run.actionName??run.actionId,status:run.status,exitCode:run.exitCode??'—'})),node('pre','run:output:'+run.id,run.output,[],{tabindex:'0'}),act('cancelProjectAction',t('external.cancelRun'),run.id)]))));
 const change=state.changeSet;
 if(change){
  children.push(section('inspector:changes',t('inspector.turnChanges'),[text('change:status',`${change.attribution} · ${change.captureStatus}`),text('change:error',change.captureError),act('restoreTurn',t('external.restoreTurn'),change.turnId),...change.files.map(file=>node('article','change:file:'+file.path,null,[text('change:path:'+file.path,file.path),act('showDiff',t('semantic.inspect'),change.turnId,file.path),...['stage','unstage','revert'].map((operation,i)=>act('fileAction',[t('external.stageFile'),t('external.unstageFile'),t('external.restoreFile')][i],change.turnId,file.path,operation))])),...change.commands.map(command=>section('change:command:'+command.id,command.command??command.toolName??t('inspector.command'),[text('change:command-status:'+command.id,command.status),node('pre','change:command-output:'+command.id,command.output)])),...change.verification.map(item=>section('change:verification:'+item.id,t('external.verificationStatus',{status:item.status}),[node('pre','change:verification-output:'+item.id,item.output)]))]));
  if(state.fileDiff)children.push(section('inspector:diff',state.fileDiff.path,[text('change:diff-reason',state.fileDiff.reason),node('pre','change:diff-content',state.fileDiff.diff,[],{tabindex:'0'}),...state.fileDiff.hunks.map(hunk=>section('change:hunk:'+hunk.index,hunk.header,[node('pre','change:hunk-content:'+hunk.index,hunk.content),...['stage','unstage','revert'].map((operation,i)=>act('hunkAction',[t('external.stageHunk'),t('external.unstageHunk'),t('external.restoreHunk')][i],change.turnId,state.fileDiff.path,String(hunk.index),operation))]))]));
 }
 children.push(text('inspector:diff-error',state.fileDiffError),state.fileDiffLoading?text('inspector:diff-loading',t('external.loadingDiff')):null,section('inspector:checkpoints',t('external.checkpoints'),state.checkpoints.map(item=>text('checkpoint:'+item.id,`${item.path} · ${item.available?t('inspector.available'):item.reason??t('inspector.unavailable')}${item.baselineDirty?t('external.baselineDirtySuffix'):''}`))),section('inspector:restores',t('inspector.restoreHistory'),state.restoreOperations.map(item=>section('restore:'+item.id,item.status==='completed'?t('inspector.restored'):item.status==='blocked'?t('inspector.restoreBlocked'):item.status==='failed'?t('inspector.restoreFailed'):item.status,[text('restore:restored:'+item.id,t('external.restoredPaths',{paths:new Intl.ListFormat(locale).format(item.restored)})),text('restore:conflicts:'+item.id,t('external.conflictPaths',{paths:new Intl.ListFormat(locale).format(item.conflicts)})),text('restore:unsupported:'+item.id,t('external.unsupportedPaths',{paths:new Intl.ListFormat(locale).format(item.unsupported)}))]))));
 return section('inspector',t('side.context'),children);
}
